using System.Text;

namespace CRAB.WebAssembly;

/// <summary>
/// Generates HTML files for running WebAssembly modules in the browser
/// </summary>
public static class HtmlGenerator
{
    /// <summary>
    /// Generate an HTML file that loads and runs a WASM module
    /// </summary>
    /// <param name="projectName">Name of the project (used in title)</param>
    /// <param name="wasmFileName">Name of the WASM file to load (default: output.wasm)</param>
    /// <param name="jsFileName">Name of the JS wrapper file (default: output.js)</param>
    /// <returns>HTML content as string</returns>
    public static string GenerateHtml(string projectName = "CRAB Project", string wasmFileName = "output.wasm", string jsFileName = "output.js")
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("    <meta charset=\"UTF-8\">");
        sb.AppendLine("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        sb.AppendLine($"    <title>{projectName} - CRAB WebAssembly</title>");
        sb.AppendLine("    <style>");
        sb.AppendLine("        body {");
        sb.AppendLine("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;");
        sb.AppendLine("            max-width: 900px;");
        sb.AppendLine("            margin: 50px auto;");
        sb.AppendLine("            padding: 20px;");
        sb.AppendLine("            background: #f5f5f5;");
        sb.AppendLine("        }");
        sb.AppendLine("        h1 {");
        sb.AppendLine("            color: #8B0000;");
        sb.AppendLine("            border-bottom: 3px solid #8B0000;");
        sb.AppendLine("            padding-bottom: 10px;");
        sb.AppendLine("        }");
        sb.AppendLine("        .container {");
        sb.AppendLine("            background: white;");
        sb.AppendLine("            padding: 30px;");
        sb.AppendLine("            border-radius: 8px;");
        sb.AppendLine("            box-shadow: 0 2px 4px rgba(0,0,0,0.1);");
        sb.AppendLine("        }");
        sb.AppendLine("        .status {");
        sb.AppendLine("            padding: 15px;");
        sb.AppendLine("            margin: 15px 0;");
        sb.AppendLine("            border-radius: 5px;");
        sb.AppendLine("            font-family: 'Courier New', monospace;");
        sb.AppendLine("        }");
        sb.AppendLine("        .loading {");
        sb.AppendLine("            background: #fff3cd;");
        sb.AppendLine("            border-left: 4px solid #ffc107;");
        sb.AppendLine("        }");
        sb.AppendLine("        .success {");
        sb.AppendLine("            background: #d4edda;");
        sb.AppendLine("            border-left: 4px solid #28a745;");
        sb.AppendLine("        }");
        sb.AppendLine("        .error {");
        sb.AppendLine("            background: #f8d7da;");
        sb.AppendLine("            border-left: 4px solid #dc3545;");
        sb.AppendLine("        }");
        sb.AppendLine("        .output {");
        sb.AppendLine("            background: #f8f9fa;");
        sb.AppendLine("            padding: 15px;");
        sb.AppendLine("            margin: 15px 0;");
        sb.AppendLine("            border-radius: 5px;");
        sb.AppendLine("            border: 1px solid #dee2e6;");
        sb.AppendLine("            font-family: 'Courier New', monospace;");
        sb.AppendLine("            white-space: pre-wrap;");
        sb.AppendLine("            max-height: 400px;");
        sb.AppendLine("            overflow-y: auto;");
        sb.AppendLine("        }");
        sb.AppendLine("        .footer {");
        sb.AppendLine("            margin-top: 30px;");
        sb.AppendLine("            padding-top: 20px;");
        sb.AppendLine("            border-top: 1px solid #dee2e6;");
        sb.AppendLine("            color: #6c757d;");
        sb.AppendLine("            font-size: 0.9em;");
        sb.AppendLine("        }");
        sb.AppendLine("    </style>");
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");
        sb.AppendLine("    <div class=\"container\">");
        sb.AppendLine($"        <h1>🦀 {projectName}</h1>");
        sb.AppendLine("        <div id=\"status\" class=\"status loading\">Loading WebAssembly module...</div>");
        sb.AppendLine("        <div id=\"output\" class=\"output\"></div>");
        sb.AppendLine("        <div class=\"footer\">");
        sb.AppendLine("            <p>Generated by <strong>CRAB Compiler</strong> - C# to WebAssembly</p>");
        sb.AppendLine("            <p>Open the browser console (F12) for more details.</p>");
        sb.AppendLine("        </div>");
        sb.AppendLine("    </div>");
        sb.AppendLine();
        sb.AppendLine($"    <script src=\"{jsFileName}\"></script>");
        sb.AppendLine("    <script>");
        sb.AppendLine("        const statusDiv = document.getElementById('status');");
        sb.AppendLine("        const outputDiv = document.getElementById('output');");
        sb.AppendLine();
        sb.AppendLine("        function updateStatus(message, type) {");
        sb.AppendLine("            statusDiv.textContent = message;");
        sb.AppendLine("            statusDiv.className = 'status ' + type;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        function appendOutput(message) {");
        sb.AppendLine("            outputDiv.textContent += message + '\\n';");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        // Override console.log to also display in page");
        sb.AppendLine("        const originalLog = console.log;");
        sb.AppendLine("        console.log = function(...args) {");
        sb.AppendLine("            originalLog.apply(console, args);");
        sb.AppendLine("            appendOutput(args.join(' '));");
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        // Load and run the WASM module");
        sb.AppendLine($"        loadAndRunWasm('{wasmFileName}')");
        sb.AppendLine("            .then(instance => {");
        sb.AppendLine("                updateStatus('✓ WebAssembly module loaded and executed successfully', 'success');");
        sb.AppendLine("            })");
        sb.AppendLine("            .catch(error => {");
        sb.AppendLine("                updateStatus('✗ Error loading WebAssembly module: ' + error.message, 'error');");
        sb.AppendLine("                console.error('Error details:', error);");
        sb.AppendLine("            });");
        sb.AppendLine("    </script>");
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");
        
        return sb.ToString();
    }
}
