<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="CLI/Program.cs" />
    <Compile Include="Core/MapSet.cs" />
    <Compile Include="Core/Orchestrator.cs" />
    <Compile Include="Core/RuleSet.cs" />
    <Compile Include="Core/TokenSet.cs" />
    <Compile Include="Dependencies/CDTk/Boilerplate/CDTk.cs" />
  </ItemGroup>

</Project>
