/**
 * WebAssembly Module Loader and Runner
 * Generated by BADGER - CRAB Compiler
 */

async function loadAndRunWasm(wasmPath) {
    try {
        // Fetch the WASM file
        const response = await fetch(wasmPath);
        const buffer = await response.arrayBuffer();
        
        // Create imports object
        const imports = {
            env: {
                memory: new WebAssembly.Memory({ initial: 1 }),
                // Add more imports as needed
            }
        };
        
        // Compile and instantiate
        const result = await WebAssembly.instantiate(buffer, imports);
        const instance = result.instance;
        
        // Log exports
        console.log('WASM module loaded successfully');
        console.log('Exports:', Object.keys(instance.exports));
        
        // Call main function if it exists
        if (instance.exports.main) {
            console.log('Calling main()...');
            const result = instance.exports.main();
            console.log('Result:', result);
            return result;
        } else {
            console.warn('No main() function found in exports');
        }
        
        return instance;
    } catch (error) {
        console.error('Error loading WASM module:', error);
        throw error;
    }
}

// Node.js compatible version
async function loadAndRunWasmNode(wasmPath) {
    const fs = require('fs');
    
    try {
        // Read WASM file
        const buffer = fs.readFileSync(wasmPath);
        
        // Create imports
        const imports = {
            env: {
                memory: new WebAssembly.Memory({ initial: 1 })
            }
        };
        
        // Compile and instantiate
        const result = await WebAssembly.instantiate(buffer, imports);
        const instance = result.instance;
        
        console.log('WASM module loaded successfully');
        console.log('Exports:', Object.keys(instance.exports));
        
        // Call main if available
        if (instance.exports.main) {
            const result = instance.exports.main();
            console.log('main() returned:', result);
            return result;
        }
        
        return instance;
    } catch (error) {
        console.error('Error:', error);
        throw error;
    }
}

// Auto-detect environment and run
if (typeof window !== 'undefined') {
    // Browser environment
    loadAndRunWasm('output.wasm').catch(console.error);
} else if (typeof require !== 'undefined') {
    // Node.js environment
    loadAndRunWasmNode('./output.wasm').catch(console.error);
}
